language: node_js
node_js:
    - stable
cache:
    yarn: true
    directories:
        - node_modules
before_script:
    - yarn global add firebase-tools
script:
    - yarn prod
after_script:
    - test $TRAVIS_PULL_REQUEST = "false" && firebase deploy --token $FIREBASE_TOKEN --non-interactive
notifications:
    webhooks: https://fathomless-fjord-24024.herokuapp.com/notify
